### ISSUE TITLE
Logic of snippet block

### ISSUE THREAD

**Issue by personafour** [hugeinc/styleguide#43] opened 2015-09-03 06:52 UTC
OS: Windows 7
Browser: Google Chrome 44.0.2403.157 m
Error: not sure if it's error or a bug, but is there way to show in snippet only nested code? For example, currently snippets works like:

```jade
ul.snippet.list_huge
    li ...
    li ...
    li ...
```

In result we get code code like this:
![image](https://cloud.githubusercontent.com/assets/3624191/9652110/0757f682-5221-11e5-828f-43aa8f38df34.png)

It would be great if snippet block can be used only as wrap to show nested code. For example:

```jade
div.snippet
    ul.some-class
        li ...
        li ...
```

will return us

```html
<ul class="some-class"><li>...</li><li>...</li></ul>
```

Thanks for answer.

**Comment by jessycormier** [comment] 2015-09-03 12:36
You can use the ability to add scripts to your modules to write a small piece of code which would remove the word "snippet" from any of the outputted snippets.

What I've done is explain in an Intro section that the snippet class is literally used to denote that they have grabbed a snippet and should be removed once moving it to production.

**Comment by caiovaccaro** [comment] 2015-09-03 22:10
Thanks @personafour and @jessycormier .

Just to confirm, your issue is that you don't want the "snippet" class to appear in the code block?

**Comment by personafour** [comment] 2015-09-04 07:30
@caiovaccaro well, actually I thought that there is a way to use ".snippet" element as wrap to show in snippet block only nested elements like:

```jade
div.snippet
    ul.some-class
        li ...
        li ...
```

```html
<ul class="some-class"><li>...</li><li>...</li></ul>
```

Of course I can parse HTML/text inside <code> and remove this class. But I thought that if it will be native feature - that would be great.

**Comment by caiovaccaro** [comment] 2015-09-11 21:10
@davegomez , I believe you have fixed that before, right?

**Comment by davegomez** [comment] 2015-09-11 22:14
I fixed an issue related to the scss placeholders to extend classes but I can check this issue.

**Comment by caiovaccaro** [comment] 2015-09-12 17:08
Actually it was @skywlkr who did a PR with that fix. @skywlkr can you take a look?

Sorry @davegomez .

**Comment by davegomez** [comment] 2015-11-08 19:03
Currently the snippets are working as expected by this thread.

This snippet code:

```
ul.snippet.some-class
  li Item 1
  li Item 2
  li Item 3
```

Is generating this output in the Styleguide:

![snippet](https://cloud.githubusercontent.com/assets/282903/11022004/6b770c3c-8621-11e5-872a-3227b75a8b7a.png)

**Comment by caiovaccaro** [comment] 2015-11-10 12:58
@personafour can you test again? Maybe you had an outdated version (our mistake).

**Comment by caiovaccaro** [comment] 2015-11-13 12:26
Closing since we can't reproduce the issue. Please reopen the ticket if the problem persist with the latest version.

**Closed by caiovaccaro** 2015-11-13 12:26 UTC
Labels: bug
