### ISSUE TITLE
Javascript error on guide loading breaks page functioning.

### ISSUE THREAD

**Issue by personafour** [hugeinc/styleguide#44] opened 2015-09-04 11:44 UTC
OS: Windows 7

Browser: 
- Chrome 45.0.2454.85 m
- Firefox 40.0.3
- IE 11/10 (Compatibility Mode)

Errors:
Chrome
![image](https://cloud.githubusercontent.com/assets/3624191/9682694/bb42e3a0-5311-11e5-953a-a7ac79a10297.png)

Fox
![image](https://cloud.githubusercontent.com/assets/3624191/9682654/7462a8b2-5311-11e5-9779-bf1c47c9fedd.png)

IE
![image](https://cloud.githubusercontent.com/assets/3624191/9682736/2111f824-5312-11e5-9003-7437d0e2d870.png)

How to.
- Download *.zip for Windows/Linux from [here](http://hugeinc.github.io/styleguide/download.html) OR
```console
git clone https://github.com/hugeinc/styleguide.git
```
- Go to styleguide/structure/_node-files, open console and do npm install
- Then do node watch.js
- Wait until "Done! Enjoy!" will be shown.
- Open http://localhost:9241/
- Open console and wait until left menu will upear.
- Done! Enjoy! :+1: 

Dependencies:
NodeJS were downloaded and installed from official site. Then I did
```console
npm install -g harp
```
and did all steps from "How to".

**Comment by davegomez** [comment] 2015-09-28 16:47
I couldn't reproduce the error using Chrome 45.0.2454.101 and Firefox 41.0.

I'm also using Node v4.1.1 and Harp 0.19.0

**Comment by caiovaccaro** [comment] 2015-10-12 00:04
@davegomez , are you using Windows or Mac?

**Comment by davegomez** [comment] 2015-10-19 22:17
@caiovaccaro I'm using OS X, maybe this is a Windows only bug.

**Comment by caiovaccaro** [comment] 2015-10-21 12:20
@davegomez I think so, do you have how to test this on a Windows machine?

**Comment by davegomez** [comment] 2015-10-21 16:13
Not really =(

**Comment by Nipher** [comment] 2015-11-06 16:23
I couldn't reproduce this...

I'm using Windows 7 
did this on IE11, IE10, chrome and firefox without any error.

I'm using node 0.12.7, but I don't think node's version would affect anything on this...

@personafour can you check if this issue is still happening?

**Comment by caiovaccaro** [comment] 2015-11-10 12:57
Seems to be related to #42

**Comment by caiovaccaro** [comment] 2015-11-13 12:26
Closing since we can't reproduce the issue. Please reopen the ticket if the problem persist with the latest version.

**Closed by caiovaccaro** 2015-11-13 12:26 UTC
Labels: bug
