### ISSUE TITLE
Struggling with errors

### ISSUE THREAD

**Issue by mattyspruce** [hugeinc/styleguide#47] opened 2015-10-08 00:20 UTC
Hey guys,

I've been trying to troubleshoot these errors all morning without any success, any help would be much appreciated.

I've tried running manually and all of the know error fixes.

LOG:

Styleguide. Welcome!
PROGRESS:50

Checking dependencies...

npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No description
npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No repository field.
npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No README data
PROGRESS:80

Let's start this thing...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8374
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at Server.listen (/Applications/MAMP/htdocs/styleguide-master/styleguide/structure/_node-files/node_modules/livereload/lib/livereload.js:70:28)
    at Object.exports.createServer (/Applications/MAMP/htdocs/styleguide-master/styleguide/structure/_node-files/node_modules/livereload/lib/livereload.js:216:12)
    at Object.module.exports.start (/Applications/MAMP/htdocs/styleguide-master/styleguide/structure/_node-files/modules/livereloader.js:12:25)
    at Object.<anonymous> (/Applications/MAMP/htdocs/styleguide-master/styleguide/structure/_node-files/watch.js:39:14)
    at Module._compile (module.js:434:26)
PROGRESS:100

Just doesn't seem to be starting up after this?

Cheers,
Matt

**Comment by caiovaccaro** [comment] 2015-10-11 13:56
Hi @mattyspruce ! Thanks for taking the time.

I see you are using the Start.app right? If so, please try changing the port, since the error says the address is already in use:

```
touch ~/.bashrc
echo 'export STYLEGUIDE_PORT=1234' >> ~/.bashrc
```

Let me know if it works.

**Comment by mattyspruce** [comment] 2015-10-12 00:05
Thanks for the reply!

I ran those lines in the start app with no luck, also tried changing the port manually. 

Updated Log:


Styleguide. Welcome!
PROGRESS:50

Checking dependencies...

npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No description
npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No repository field.
npm WARN package.json HugeStyleguideNodeRunner@2.0.0 No README data
PROGRESS:80

Let's start this thing...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8374
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at Server.listen (/Applications/MAMP/htdocs/styleguide-master/styleguide/structure/_node-files/node_modules/livereload/lib/livereload.js:70:28)
    at Object.exports.createServer (/Applications/MAMP/htdocs/styleguide-master/styleguide/structure/_node-files/node_modules/livereload/lib/livereload.js:216:12)
    at Object.module.exports.start (/Applications/MAMP/htdocs/styleguide-master/styleguide/structure/_node-files/modules/livereloader.js:12:25)
    at Object.<anonymous> (/Applications/MAMP/htdocs/styleguide-master/styleguide/structure/_node-files/watch.js:39:14)
    at Module._compile (module.js:434:26)
PROGRESS:100

**Comment by caiovaccaro** [comment] 2015-10-12 00:31
Do you have any other livereload running?

Thanks!

**Comment by mattyspruce** [comment] 2015-10-12 00:37
I occasionally use Browser Sync but haven't had it running?

**Comment by mattyspruce** [comment] 2015-10-12 00:51
FYI Browser Sync uses:

[BS] Access URLs:
 -------------------------------------
Local: http://localhost:3000
External: http://192.168.0.20:3000
 -------------------------------------
 UI: http://localhost:3001
 UI External: http://192.168.0.20:3001

**Comment by davegomez** [comment] 2015-11-03 21:42
Hi @mattyspruce can you give me any update on this error please, show a way to reproduce it maybe?

Thanks!

**Comment by davegomez** [comment] 2015-11-08 19:06
Couldn't reproduce this errors in Windows 10 with Nodejs v4.2.2

**Comment by caiovaccaro** [comment] 2015-11-10 12:59
@mattyspruce can you download again and do one more test? Let us know your environment as well.

**Comment by caiovaccaro** [comment] 2015-11-13 12:27
Closing since we can't reproduce the issue. Please reopen the ticket if the problem persist with the latest version.

**Closed by caiovaccaro** 2015-11-13 12:27 UTC
Labels: bug
